[package]
name = "simple-kl-terminal-runner-extension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shutil = "0.1.2"
simple_kl_rs = {path = "/home/lighttigerxiv/Development/Crates/simple-kl-rs"}
